In [1]:
set = {"Aman","222",777,400.4}
tuple = tuple(set)
print(tuple)

(400.4, 777, 'Aman', '222')


In [2]:
dict = {"Roll no.":"CB.EN.U4CSE22544","Lastname":"Venkatesh","Firstname":"Shreya","DOB":"2004-05-15"}
print(dict.keys(),"\n",dict.values())

dict_keys(['Roll no.', 'Lastname', 'Firstname', 'DOB']) 
 dict_values(['CB.EN.U4CSE22544', 'Venkatesh', 'Shreya', '2004-05-15'])


In [3]:
import numpy as np
np.random.seed(1000)
arr = np.random.randint(0,10,size=(3,3))
print("Integer array:",arr)
arr = np.random.rand(3,3)
print("Floating array:",arr)

Integer array: [[3 7 7]
 [0 1 0]
 [9 8 9]]
Floating array: [[0.39719446 0.2331322  0.84174072]
 [0.20708234 0.74246953 0.39215413]
 [0.18225652 0.74353941 0.06958208]]


In [4]:
import random as rm
num = rm.random()
#num_py= np.random.uniform(0,1)
abs_value = abs(-1234)
#print(num_py)
print("Random Number:",num)
print("Absolute value of -1234:",abs_value)

Random Number: 0.9338746557642025
Absolute value of -1234: 1234


In [5]:
N = np.random.randint(20,90) 
print(N)

50


In [6]:
set = [11,12,13,14,15]
unique_nums = rm.sample(set,3)
print("Unique elements: ",unique_nums)

rm.shuffle(set)
print("Shuffled set: ",set)

print("Random Number: ",rm.choice(set))

Unique elements:  [11, 14, 13]
Shuffled set:  [14, 11, 15, 13, 12]
Random Number:  15


In [7]:
text = "the king is dead, long live the king"
with open('deadking.txt','w') as file:
    file.write(text)
with open('deadking.txt','r') as file:
    readtxt = file.read()

print(readtxt)

the king is dead, long live the king


In [8]:
def illustrative_func():
    
    num = -1
    if(num == 1 or num==0):
        print("binary digit ")
    elif num>1:
        print("integer")
    else:
        print("negative number")
    
    print("skipping the number 1:")
    for i in range(10):
        if(i==1):
            continue
        print(i,end=" ")
        
    print("\nwhile with break:")
    c = 0
    while(c <=5):
        if c == 4:
            break
        print(c,end=" ")
        c += 1
        
illustrative_func()

negative number
skipping the number 1:
0 2 3 4 5 6 7 8 9 
while with break:
0 1 2 3 

In [9]:
text = "the king is dead, long live the king"
print(text)
print("the first character of the string:",text[0])
print("characters starting from 3rd to 5th:",text[2:5])
print("string starting from 3rd character:",text[2:])
print("the words:",text.split())

the king is dead, long live the king
the first character of the string: t
characters starting from 3rd to 5th: e k
string starting from 3rd character: e king is dead, long live the king
the words: ['the', 'king', 'is', 'dead,', 'long', 'live', 'the', 'king']


In [10]:
arr=np.array([1.0,4.0,5.0,8.0])
print("Sliced elements:",arr[:2])

Sliced elements: [1. 4.]


In [11]:
_2d=np.array([[1,2,3],[4,5,6]])
print(_2d)

[[1 2 3]
 [4 5 6]]


In [12]:
print("second row:",_2d[1])

float = np.array([_2d[0,1],_2d[1,1]],dtype="float")
print(float)

print("length of the 2d array:",len(_2d))

second row: [4 5 6]
[2. 5.]
length of the 2d array: 2


In [13]:
arr1d = np.arange(4)
arr2d=arr1d.reshape((2,2))
print("1d array:",arr1d)
print("2d array:\n",arr2d,end=" \n")
print("transpose of 2d array:\n",arr2d.T)

1d array: [0 1 2 3]
2d array:
 [[0 1]
 [2 3]] 
transpose of 2d array:
 [[0 2]
 [1 3]]


In [14]:
array = np.array([1,2,3])
print(array)

[1 2 3]


In [15]:
swap = np.full_like(array,9)
print(swap)

[9 9 9]


In [16]:
a = np.array([2,4,5])
print("Sum of array elements",np.sum(a))

Sum of array elements 11


In [17]:
a = np.array([77,74,75])
print("Product of array elements",np.prod(a))

Product of array elements 427350


In [18]:
desc = np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print("Mean:",np.mean(desc))
print("median:",np.median(desc))
print("standard deviation:",np.std(desc))
print("Variance:",np.var(desc))
print("Min:",np.min(desc))
print("Max:",np.max(desc))
print("argmin:",np.argmin(desc))
print("argmax:",np.argmax(desc))

Mean: 12.461538461538462
median: 2.0
standard deviation: 19.165736192147232
Variance: 367.32544378698225
Min: 1
Max: 56
argmin: 1
argmax: 12


In [19]:
arr = np.array([1,1,4,5,5,5,7])
unique = np.unique(arr)
print(np.sort(unique))

[1 4 5 7]


In [20]:
a1 = np.array([1,2,3])
a2=np.array([0,1,1])
print("dot product:",np.dot(a1,a2))

dot product: 5


In [21]:
a = np.array([[2,-12],[1,-5]])
eigenvalues,eigenvectors = np.linalg.eig(a)
print("eigenvalues:",eigenvalues)
print("eigenvectors:\n",eigenvectors,end="\n")

eigenvalues: [-1. -2.]
eigenvectors:
 [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


In [22]:
a = np.array([[11, 22, 11, 31], [25, 33, 31, 28]],dtype="float")
print("correlation coeff:\n",np.corrcoef(a))

correlation coeff:
 [[1.         0.15997968]
 [0.15997968 1.        ]]
