# LAB1

In [ ]:
#Create a list of 10 integers. Write a program to find the maximum and minimum
# numbers in the list.

import random
numbers = random.sample(range(1, 100), 10)
print("The list of numbers is: ", numbers)
min_number = min(numbers)
max_number = max(numbers)
print("The minimum number is: ", min_number)
print("The maximum number is: ", max_number)


The list of numbers is:  [95, 23, 82, 72, 67, 14, 36, 31, 54, 47]
The minimum number is:  14
The maximum number is:  95


In [ ]:
og=[1,2,3,4,5]
og=og[::-1]
print(og)


[5, 4, 3, 2, 1]


In [ ]:

my_tuple = (10, 20, 30, 40, 50)

my_list = list(my_tuple)

print("The list is: ", my_list)


The list is:  [10, 20, 30, 40, 50]


In [ ]:
tuple = (5,48,43,79,29)
tuple = sorted(tuple)
print(tuple[len(tuple)-2])

48


In [ ]:
d = {'a':1,'b':2,'c':3,'d':4,'e':5}
max = 0
key = ''
for i in d:
    if d[i] > max:
        max = d[i]
        key = i
print(key)

e


In [ ]:
d1 = {'a':1,'b':2}
d2 = {'c':3,'d':4}
d1.update(d2)
print(d1)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [ ]:
set1 = {1,2,3,4,5}
set2 = {3,4,5,6,7}
print(set1.union(set2))
print(set1.intersection(set2))

{1, 2, 3, 4, 5, 6, 7}
{3, 4, 5}


In [ ]:
# Write a program to check if a set is a subset of another set.

set1 = {1, 2, 3}
set2 = {1, 2, 3, 4, 5}

if set1.issubset(set2):
  print("set1 is a subset of set2")
else:
  print("set1 is not a subset of set2")


set1 is a subset of set2


In [ ]:
string = input()
vowels = 0
for i in string:
    if i == 'a' or i == 'e' or i == 'i' or i == 'o' or i == 'u':
        vowels += 1
print(vowels)

hello
2


In [ ]:
string = input()
if string == string[::-1]:
    print('True')
else:
    print('False')

wow
True


In [ ]:
string = input()
sub = input()
new = input()
print(string.replace(sub,new))

Shreya
S
A
Ahreya


In [ ]:
s = input()
print("First 3 characters",s[:3])
print("Last 3 characters",s[-3:])

shreya
First 3 characters shr
Last 3 characters eya


In [ ]:
x,y =input().split( )
print("add",int(x)+int(y))
print("subt",int(x)-int(y))
print("mul",int(x)*int(y))
print("div",int(x)//int(y))

23 45
add 68
subt -22
mul 1035
div 0


In [ ]:
radius = int(input())
pi = 3.14
area = pi * radius * radius
print("area:",area)

5
area: 78.5


In [ ]:
#Write a program to sort a list of strings based on the length of the strings
num = int(input())
fact = 1
for i in range(1,num+1):
    fact = fact * i
print(fact)

5
120


In [ ]:
a,b,c = map(int,input().split())
formula = (b**2)-(4*a*c)
print(formula)

2 3 4
-23


In [ ]:
import random
list = []
for i in range(5):
    list.append(random.randint(1,100))
print(list)

[47, 17, 80, 16, 39]


In [ ]:
import random
list = []
for i in range(1):
    list.append(random.randint(1,6))
print(list)

[4]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Mean:",np.mean(arr))
print("Standard deviation:",np.std(arr))

Mean: 5.5
Standard deviation: 2.8722813232690143


In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12])
print(arr1*arr2)

[ 7 16 27 40 55 72]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.flatten())

[1 2 3 4 5 6]


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

sum_arr = arr1 + arr2
print("Sum of arrays:", sum_arr)

diff_arr = arr1 - arr2
print("Diff of arrays:", diff_arr)

Sum of arrays: [ 6  8 10 12]
Diff of arrays: [-4 -4 -4 -4]


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

prod_arr = arr1 * arr2
print("Prod of arrays:", prod_arr)

Prod of arrays: [ 5 12 21 32]


In [ ]:


import numpy as np

# Create a 5x5 numpy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(5, 5))
print("Original array:\n", array)

diagonal_elements = np.diag(array)
print("\nDiagonal elements:", diagonal_elements)


Original array:
 [[ 5  6 66 56 26]
 [90 89 54 21 50]
 [37 80 27 65 15]
 [99 83 13  3 73]
 [92 63 90  2 32]]

Diagonal elements: [ 5 89 27  3 32]


In [ ]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr[arr % 2 == 0] = -1

# Print the modified array
print(arr)


[ 1 -1  3 -1  5 -1  7 -1  9 -1]


In [ ]:
# Write a program to create a dictionary where the keys are the first 10 letters of the
# alphabet and the values are random integers between 1 and 100.

import random

my_dict = {}

# Iterate over the first 10 letters of the alphabet
for letter in 'abcdefghij':
  random_number = random.randint(1, 100)
  my_dict[letter] = random_number

# Print the dictionary
print(my_dict)


{'a': 30, 'b': 94, 'c': 97, 'd': 44, 'e': 26, 'f': 80, 'g': 40, 'h': 18, 'i': 6, 'j': 20}


In [ ]:

result = [(x, x**2) for x in range(1, 11)]
print(result)


[(1, 1), (2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64), (9, 81), (10, 100)]


In [ ]:
#Write a program to find the common characters between two strings.
s1 = input()
s2 = input()
s1 = set(s1)
s2 = set(s2)
print(s1.intersection(s2))

hiii
hiieee
{'h', 'i'}


In [ ]:
#Write a program to sort a list of strings based on the length of the strings.
list = input().split()
list.sort(key=len)
print(list)

hi hello how r u
['r', 'u', 'hi', 'how', 'hello']
